### ISSUE TITLE
ExportSDF

### ISSUE THREAD

**Issue by tiwylli** [cg-tuwien/ppsurf#2]
Would it be possible to export the predicted sdf directly ?

**Comment by ErlerPhilipp** [comment]
Hi @tiwylli!

You can simply export the volume used for marching cubes.

Go to `source/poco_utils.py`, line 96 (marching cubes call). Add this line before and you'll get the volume exported as a numpy array:
```
np.save('your/path/to/volume.npy', volume)
```

Note that the volume will be a bit different than the mesh because the cleaning is omitted. 
Also, the volumes are very inefficient and will be quite large on the hard drive.

Does this solve your issue?

**Comment by tiwylli** [comment]
Thank you so much for your answer. 
Yes I figured the volume was what I needed. I'm working on a project with input pointclouds and wanted to estimate an SDF, but from what I understand, it's easier to use a mesh as input to estimate an SDF. 

Have a great weekend
