### ISSUE TITLE
train own dataset

### ISSUE THREAD

**Issue by thousanddrowned** [cg-tuwien/ppsurf#3]
How to make my own dataset, and how to train it. Could you give some steps to adjust the parameters? Thanks much!

**Comment by ErlerPhilipp** [comment]
Hi @thousanddrowned!

If you only need to reconstruct your own point cloud, please see the Readme for command-line options.

I understand that you want to train on your own dataset. The datasets are still the same as in our predecessor work "Points2Surf. Please see the Readme there: https://github.com/ErlerPhilipp/points2surf?tab=readme-ov-file#make-your-own-datasets
There are some issues regarding new datasets, and some tricky aspects about the parameters. Please check the P2S issues, especially this one: https://github.com/ErlerPhilipp/points2surf/issues/34
Let me know if you need more help.

Which parameters do you want to adjust? You can refine a model by loading an existing one for the training. Simply add `--ckpt_path {path}` to the train command. Otherwise, the default parameters should be fine.

**Comment by thousanddrowned** [comment]
Thanks your reply.I have tried to train on my own dataset about 150 epoch, but the reconstruction is not well, even worse than the checkpoint you provide, how can i solve it. What' more , as you mentioned above, i tried p2s too, but i can't find the mesh results, only point cloud.

**Comment by ErlerPhilipp** [comment]
PPSurf is better than P2S in every regard. You don't need to bother with P2S, except for dataset generation.

Note that PPSurf is meant for single, solid objects, i.e. objects with a clear inside and outside. If you're trying to reconstruct e.g. streets and landscapes, you might get bad results. Also, the number of objects is important. The P2S dataset contains 4950 objects for training. I think you shouldn't go below 1000 objects. Can you give more details about the dataset?

**Comment by thousanddrowned** [comment]
My dataset consists of point cloud data related to the surface of carbon fiber. Since the original point cloud data is very large, in the tens of millions of points, I split it into several smaller chunks to use as the dataset. Could you provide suggestions on adjustments to the network or parameters for this type of data? Thanks again!
![github](https://github.com/user-attachments/assets/cc50a3ec-16e8-4b9e-85c0-b4263caeb2b9)
![gt](https://github.com/user-attachments/assets/0770eb5a-3ccb-4795-adbb-3491f104e1ae)

**Comment by ErlerPhilipp** [comment]
This seems very thin. With the limited resolution of the SDF grid, it can easily miss the interior of the sheet. I assume, you don't care about the volume but you need one side accurately. Is this correct?

Here are a few ideas:

1. You could try adding synthetic objects to the dataset. These objects could be boxes of varying thickness + some distortions.
2. Align the sheets with the XY-plane and disable random rotation data augmentation. I guess it would become better because it doesn't need to learn the whole volume, just near the plane.
3. If you don't care about the thickness, extrude the sheets to e.g. -0.5 on Z.
4. Use a different method. Maybe something that works with thin sheets, unsigned distances or heightmaps. If I remember correctly, Convolutional Occupancy Networks has a 2.5D option. https://github.com/autonomousvision/convolutional_occupancy_networks

**Comment by thousanddrowned** [comment]
Thank you very much for your help. I will try the methods you taught me. If I encounter any issues, can I ask you again?

**Comment by ErlerPhilipp** [comment]
Sure, just re-open the issue then or create a new one. However, I can't really help with Convolutional Occupancy Networks or other methods.

Happy to help!
